import type { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";
import { MixIcon, PaperPlaneIcon, RocketIcon } from "@radix-ui/react-icons";
import { styled } from "@config/stitches.config";
import Container from "@components/Container";
import Card from "@src/components/Card";

const Span = styled("span", {});
const Grid = styled("div", {
  display: "grid",
  alignItems: "center",
  gridTemplateColumns: "repeat(6, 1fr)",
  gridGap: "24px 16px",
  zIndex: 0,
});

const Content = styled("div", {
  gridColumn: "span 6",
  "@lg": {
    gridColumn: "span 4",
  },
});

const Title = styled("div", {
  marginBottom: 24,
});

const Text = styled("p", {
  margin: 0,
  color: "$text",
  fontSize: 16,
  lineHeight: 1.8,

  variants: {
    heading: {
      true: {
        fontFamily: "$mont",
        fontWeight: 700,
        lineHeight: 1.25,
      },
    },
  },
});

const word = {
  display: "inline-block",
  marginRight: 16,
  "&:first-letter": {
    color: "$primary",
  },
  "@md": { marginRight: 16 },
};

const Links = styled("div", {
  gridColumn: "span 6",
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gridTemplateRows: "repeat(2, 125px)",
  gridTemplateAreas: `
    "projects projects"
    "skills contact"
  `,
  gridGap: "16px 16px",

  "@lg": {
    gridColumn: "span 2",
  },
});

const Link = styled(Card, {
  textDecoration: "none",
  padding: "18px 24px",
  display: "flex",
  justifyContent: "space-between",
  alignItems: "space-between",
  flexDirection: "column",

  "&:hover": {
    boxShadow: `0px 0px 16px $colors$primary`,
    transform: "scale(1.05)",
  },
});

const Icon = styled("span", {
  color: "$primary",
  width: 32,
  height: 32,
  display: "inline-flex",
  "& svg": {
    width: "100%",
    height: "100%",
  },
});

const Home: NextPage = () => {
  return (
    <Container css={{ display: "flex", alignItems: "center" }}>
      <Head>
        <title>Home | JeanTivan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid>
        <Content>
          <Title>
            <Text
              as="h1"
              heading
              css={{ fontSize: 56, "@lg": { fontSize: 64 } }}
            >
              Jean Paul Tivan
            </Text>
            <Text
              as="h2"
              css={{ fontSize: 28, "@lg": { fontSize: 32 } }}
              heading
            >
              <Span css={word}>Frontend</Span>
              <Span css={word}>Developer</Span>
            </Text>
          </Title>
          <Text
            css={{
              color: "$textSecondary",
              "@md": {
                fontSize: 18,
              },
            }}
          >
            Vestibulum rhoncus non dolor eget finibus. Vestibulum quis dolor
            nibh. Sed tempus orci eget orci euismod fringilla. Sed varius est
            leo, vitae sagittis diam efficitur sed. Vivamus risus ante,
            sollicitudin at dapibus eget, egestas ac nulla. Aliquam at neque
            non.
          </Text>
        </Content>

        <Links>
          <NextLink href="/projects" passHref legacyBehavior>
            <Link as="a" css={{ gridArea: "projects" }}>
              <Icon>
                <RocketIcon />
              </Icon>
              <Text as="h3" heading css={{ fontSize: 20 }}>
                Projects
              </Text>
            </Link>
          </NextLink>

          <NextLink href="/skills" passHref legacyBehavior>
            <Link as="a" css={{ gridArea: "skills" }}>
              <Icon>
                <MixIcon />
              </Icon>
              <Text as="h3" heading css={{ fontSize: 20 }}>
                Skills
              </Text>
            </Link>
          </NextLink>
          <NextLink href="/contact" passHref legacyBehavior>
            <Link as="a" css={{ gridArea: "contact" }}>
              <Icon>
                <PaperPlaneIcon />
              </Icon>
              <Text as="h3" heading css={{ fontSize: 20 }}>
                Contact
              </Text>
            </Link>
          </NextLink>

          <Span
            css={{
              gridColumn: "1 / 3",
              gridRow: "1 / 3",
              width: "100%",
              height: "100%",
              maxWidth: 280,
              maxHeight: 280,
              display: "block",
              color: "$primary",
              zIndex: -1,
              transform: "translate(50%, 10%)",
              "& svg": {
                stroke: "$primary",
              },
            }}
          >
            <svg
              width="100%"
              height="100%"
              viewBox="0 0 280 280"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle cx="140" cy="140" r="136" strokeWidth="4" />
            </svg>
          </Span>
        </Links>
      </Grid>
    </Container>
  );
};
export default Home;
